# Generated by Django 5.2.8 on 2025-12-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_skill_futurecompetency_employeeskill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={"ordering": ["id"]},
        ),
    ]
